baseURL = "https://thefuture.build/"
languageCode = "en-us"
title = "Build the Future"

disableHugoGeneratorInject = true
disableKinds = ["taxonomy", "taxonomyTerm"]
relativeURLs = true
 
enableEmoji = true
enableRobotsTXT = true

[outputs]
home = ["HTML","RSS"]

[params]
description = "UC Berkeleyâ€™s student-run entrepreneurship hub."
banner = "/images/banner.png"

[menu]
  # Main Menu

  [[menu.main]]
      name = "Home"
      url = "/"
      weight = 1

  [[menu.main]]
      name = "About"
      url = "/about/"
      weight = 3

  [[menu.main]]
      name = "DeCal"
      url = "/decal/"
      weight = 4

  [[menu.main]]
      name = "Podcast"
      url = "/podcast/"
      weight = 5

  [[menu.main]]
      name = "Blogs"
      url = "/blogs/"
      weight = 6
      
  [[menu.main]]
      name = "Community"
      url = "/community/"
      weight = 7



